version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
    - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
    - "dependencies"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    versioning-strategy: widen
